workflows:
  ios_simulator_screens:
    name: iOS Simulator - Build + Screens
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: "3.19.0"
      xcode: latest
      cocoapods: default
    cache:
      cache_paths:
        - $HOME/Library/Caches/CocoaPods
        - ~/.cocoapods
        - ios/Pods
        - $HOME/.pub-cache
        - build/ios/Build
    scripts:
      - name: Flutter pub get
        script: |
          flutter --version
          flutter pub get || true
      - name: Install CocoaPods
        script: |
          cd ios
          pod --version
          pod install --clean-install --repo-update
      - name: Verify Pods flags
        script: |
          cd ios
          if grep -R -- "-GCC_WARN_INHIBIT_ALL_WARNINGS" Pods -n; then
            echo "Invalid '-GCC_WARN_INHIBIT_ALL_WARNINGS' flag found in Pods. Failing early."
            exit 1
          fi
      - name: Clean response files
        script: |
          cd ios
          echo "ðŸ§¹ Cleaning .resp files to strip '-GCC_WARN_INHIBIT_ALL_WARNINGS'"
          find build -name '*.resp' -type f 2>/dev/null | while read -r f; do
            if grep -q -- "-GCC_WARN_INHIBIT_ALL_WARNINGS" "$f"; then
              echo "Cleaning $f"
              sed -i '' 's/-GCC_WARN_INHIBIT_ALL_WARNINGS//g' "$f"
            fi
          done || true
      - name: Xcode diagnostics
        script: |
          xcodebuild -version
          xcodebuild -showsdks
          xcodebuild -list -workspace ios/Runner.xcworkspace || xcodebuild -list -project ios/Runner.xcodeproj || true
          xcodebuild -showdestinations -workspace ios/Runner.xcworkspace -scheme Runner -sdk iphonesimulator || true
      - name: Create & boot simulator
        script: |
          echo "ðŸ” Selecting available iOS runtime..."
          RUNTIMES=$(xcrun simctl list runtimes | grep -E '^iOS [0-9]+' | grep -v unavailable | sed -nE 's/.*(com\.apple\.CoreSimulator\.SimRuntime\.iOS-[0-9-]+).*/\1/p' | tail -r)
          if [ -z "$RUNTIMES" ]; then
            echo "No available iOS simulators found"
            exit 1
          fi
          DEVICE_NAMES=("iPhone 15" "iPhone 14" "iPhone 15 Pro" "iPhone SE (3rd generation)")
          CREATED=""
          for RUNTIME_ID in $RUNTIMES; do
            for NAME in "${DEVICE_NAMES[@]}"; do
              LINE=$(xcrun simctl list devicetypes | grep -F -i "$NAME (" | head -1)
              if [ -n "$LINE" ]; then
                DTYPE_ID=$(echo "$LINE" | tr '()' '\n' | grep -E 'com\.apple\.CoreSimulator\.SimDeviceType\.' | head -1)
              else
                DTYPE_ID=""
              fi
              [ -z "$DTYPE_ID" ] && continue
              if DEVICE_UDID=$(xcrun simctl create "CM iPhone" "$DTYPE_ID" "$RUNTIME_ID" 2>/dev/null); then
                CREATED=1
                DEVICE_NAME="$NAME"
                SELECTED_RUNTIME="$RUNTIME_ID"
                break 2
              fi
            done
          done
          if [ -z "$CREATED" ]; then
            echo "Failed to create simulator"
            exit 1
          fi
          xcrun simctl boot "$DEVICE_UDID" || true
          xcrun simctl bootstatus "$DEVICE_UDID" -b
          echo "export DEVICE_UDID=\"$DEVICE_UDID\"" >> $CM_ENV
          echo "export DEVICE_NAME=\"$DEVICE_NAME\"" >> $CM_ENV
          echo "export SELECTED_RUNTIME=\"$SELECTED_RUNTIME\"" >> $CM_ENV
          # Derivar OS_VERSION (ex.: com.apple.CoreSimulator.SimRuntime.iOS-18-1 -> 18.1)
          OS_VERSION=$(echo "$SELECTED_RUNTIME" | sed -nE 's/.*iOS-([0-9]+)-([0-9]+).*/\1.\2/p')
          if [ -z "$OS_VERSION" ]; then
            OS_VERSION=$(echo "$SELECTED_RUNTIME" | sed -nE 's/.*iOS-([0-9]+)-([0-9]+).*/\1.\2/p')
          fi
          echo "export OS_VERSION=\"$OS_VERSION\"" >> $CM_ENV
      - name: Build iOS (Debug, simulator)
        script: |
          cd ios
          source $CM_ENV || true
          echo "DEVICE_UDID=$DEVICE_UDID"
          echo "DEVICE_NAME=$DEVICE_NAME"
          echo "OS_VERSION=$OS_VERSION"
          set -e
          if [ -n "$DEVICE_UDID" ]; then
            echo "ðŸ“± Building for simulator UDID: $DEVICE_UDID"
            xcodebuild -workspace Runner.xcworkspace -scheme Runner -configuration Debug -sdk iphonesimulator -destination "id=$DEVICE_UDID" -arch arm64 -derivedDataPath build clean build | tee xcodebuild.log
          elif [ -n "$DEVICE_NAME" ] && [ -n "$OS_VERSION" ]; then
            echo "ðŸ“± Building for simulator: $DEVICE_NAME, iOS $OS_VERSION"
            xcodebuild -workspace Runner.xcworkspace -scheme Runner -configuration Debug -sdk iphonesimulator -destination "platform=iOS Simulator,name=$DEVICE_NAME,OS=$OS_VERSION" -arch arm64 -derivedDataPath build clean build | tee xcodebuild.log
          else
            echo "ðŸ“± Building for generic iOS Simulator"
            xcodebuild -workspace Runner.xcworkspace -scheme Runner -configuration Debug -sdk iphonesimulator -destination "generic/platform=iOS Simulator" -arch arm64 -derivedDataPath build clean build | tee xcodebuild.log
          fi
          echo "ðŸ§¹ Post-build: cleaning any .resp files that may have been recreated"
          find build -name '*.resp' -type f 2>/dev/null -exec grep -l -- "-GCC_WARN_INHIBIT_ALL_WARNINGS" {} \; | while read -r f; do
            echo "Re-cleaning $f"
            sed -i '' 's/-GCC_WARN_INHIBIT_ALL_WARNINGS//g' "$f"
          done || true
          SIMULATOR_APP_PATH="build/ios/Build/Products/Debug-iphonesimulator/Runner.app"
          if [ ! -d "$SIMULATOR_APP_PATH" ]; then
            echo "App not built at $SIMULATOR_APP_PATH"
            exit 1
          fi
      - name: Install and launch
        script: |
          DEVICE_ID=${DEVICE_UDID:-booted}
          SIMULATOR_APP_PATH="build/ios/Build/Products/Debug-iphonesimulator/Runner.app"
          BUNDLE_ID=$(/usr/libexec/PlistBuddy -c 'Print:CFBundleIdentifier' "$SIMULATOR_APP_PATH/Info.plist" 2>/dev/null || echo "com.safeplate.safeplate")
          xcrun simctl install "$DEVICE_ID" "$SIMULATOR_APP_PATH" || xcrun simctl install booted "$SIMULATOR_APP_PATH"
          xcrun simctl launch "$DEVICE_ID" "$BUNDLE_ID" || true
      - name: Capture media
        script: |
          set -e
          DEVICE_ID=${DEVICE_UDID:-booted}
          mkdir -p cm-artifacts
          xcrun simctl io "$DEVICE_ID" screenshot cm-artifacts/screenshot.png || true
          xcrun simctl io "$DEVICE_ID" screenshot cm-artifacts/screenshot2.png || true
          xcrun simctl io "$DEVICE_ID" recordVideo --type=mp4 cm-artifacts/demo.mp4 & VID=$!
          sleep 12
          kill -INT $VID || true
          wait $VID || true
      - name: Package Runner.app
        script: |
          tar -czf cm-artifacts/Runner.app.tgz -C build/ios/Build/Products/Debug-iphonesimulator Runner.app
      - name: Cleanup simulator
        script: |
          xcrun simctl shutdown "$DEVICE_UDID" || true
          xcrun simctl delete "$DEVICE_UDID" || true
    artifacts:
      - cm-artifacts/**
      - xcodebuild.log
