name: SafePlateNative
options:
  deploymentTarget:
    iOS: "14.0"
 
packages:
  MapboxMaps:
    url: https://github.com/mapbox/mapbox-maps-ios
    from: 11.8.0
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk
    from: 10.0.0

targets:
  SafePlateNative:
    type: application
    platform: iOS
    sources:
      - path: Sources/SafePlateNative
    resources:
      - path: Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.safeplate.safeplate
        INFOPLIST_FILE: Resources/Info.plist
        CODE_SIGNING_ALLOWED: NO
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: "$(inherited) USE_MAPBOX"
    dependencies:
      - package: MapboxMaps
        product: MapboxMaps
      - package: Firebase
        product: FirebaseCore
      - package: Firebase
        product: FirebaseAuth
  SafePlateNativeUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: Tests/SafePlateNativeUITests
    settings:
      base:
        TEST_TARGET_NAME: SafePlateNative
        GENERATE_INFOPLIST_FILE: YES
        CODE_SIGNING_ALLOWED: NO
    dependencies:
      - target: SafePlateNative

schemes:
  SafePlateNative:
    build:
      targets:
        SafePlateNative: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - name: SafePlateNativeUITests
